@REM   WARNING   this file is automatically generated by RT-Druid

@REM   If you want modify this file, you should move it to a safe folder,
@REM   like the project's root, and update the path inside the project 
@REM   properties "C/C++ Make Project" -> "Build command"
@REM   i.e.   ${workspace_loc:multi_3}/cygwin_make.bat

@set EE_BASH_PATH=C:\cygwin\bin\bash

@%EE_BASH_PATH% -c "/bin/bash --login -c \"cd \\\"$PWD\\\"; make %1 %2 %3 %4\""
