@REM   WARNING   this file is automatically generated by RT-Druid

@REM   If you want modify this file, you should move it to a safe folder,
@REM   like the project's root, and update the path inside the project 
@REM   properties "C/C++ Make Project" -> "Build command"
@REM   i.e.   ${workspace_loc:pic32_lwip_udp_demo}/make_launcher.bat

@set EE_BASH_PATH=C:\cygwin\bin\bash

@if EXIST %EE_BASH_PATH%.exe goto endok

@echo %EE_BASH_PATH% not found.

@echo Trying c:\cygwin\bin\bash.exe
@set EE_BASH_PATH=c:\cygwin\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo Trying c:\cygwin\usr\bin\bash.exe
@set EE_BASH_PATH=c:\cygwin\usr\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo Trying d:\cygwin\bin\bash.exe
@set EE_BASH_PATH=d:\cygwin\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo Trying d:\cygwin\usr\bin\bash.exe
@set EE_BASH_PATH=d:\cygwin\usr\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo ERROR: bash not found.
@echo Please check the location of your cygwin installation and enter it in Eclipse in "Windows/Preferences/RT-Druid/Cygwin paths".
@exit

:endok
@echo %EE_BASH_PATH% found!
@%EE_BASH_PATH% -c "/bin/bash --login -c \"cd `/bin/cygpath/ -ms \"$PWD\"`; make %1 %2 %3 %4\""
