###
### Setting EEOPT variable:
###

EEOPT =

## ROM data
## EEOPT += __NO_ROM_DATA__

## Stack
EEOPT += __MULTI__

## debug
EEOPT += __DEBUG__

## Scheduling
EEOPT += __EDF__

## Time support
EEOPT += __TIME_SUPPORT__

## Architecture
EEOPT += __H8__

## Play notes
EEOPT += __PLAY_NOTE_SUPPORT__

## Play buffer
EEOPT += __PLAY_BUFFER_SUPPORT__

## motors with precise variable power
EEOPT += __MOTOR_C_PWM_USED__

## motors with precise variable power
EEOPT += __MOTOR_A_PWM_USED__

## A/D converter
EEOPT += __AD_SUPPORT__

## use double fixed point number
EEOPT += __DOUBLE_FIXED_USED__

## timerB user function
EEOPT += __TIMER_B_USER_FUNCTION_USED__

APP_SRCS = code.c inithal.c initkern.c set_hand.s handlers.c

include $(EEBASE)/config/config.mak





