###
### Setting EEOPT variable:
###

EEOPT =

## ROM data
#EEOPT += __NO_ROM_DATA__

## Stack
EEOPT += __MONO__

## debug
##EEOPT += __DEBUG__

## Scheduling
EEOPT += __EDF__

## Time support
EEOPT += __TIME_SUPPORT__

## Architecture
EEOPT += __H8__

## Play notes
EEOPT += __PLAY_NOTE_SUPPORT__

## Play buffer
##EEOPT += __PLAY_BUFFER_SUPPORT__

## PWM motor control 
EEOPT += __MOTOR_A_VP_USED__

## PWM motor control
EEOPT += __MOTOR_C_PWM_USED__

## A/D converter
##EEOPT += __AD_SUPPORT__

## 8bit timer channel 1 support
##EEOPT += __T81_SUPPORT__

## use double fixed point number
##EEOPT += __DOUBLE_FIXED_USED__

## this application use timer B user function for periodic thread activation
EEOPT += __TIMER_B_USER_FUNCTION_USED__

APP_SRCS = code.c inithal.c initkern.c set_hand.s handlers.c

include $(EEBASE)/config/config.mak





