# Author: 2002 Paolo Gai
# Rules Usage: all (build into the out dir), clean (remove the out dir)

EELIB = BINARY_OO1_CONF
EEOPT = DEBUG

APP_SRCS = initkern.c code.c threads.c inithal.c
THUMB_SRCS =

include $(EEBASE)/pkg/cfg/rules.mk
